### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ggggamer** [ggggamer/AssetPreview#21]
- [ ] Add hierarchy tree  and draw call tree.

- [ ] Add draw call tree feature.

- [ ] Add MBG schema to show bullet paths.

- [ ] Spine slot binding and IK binding preview.
