### ISSUE TITLE
TODO: Crazy Storm schema

### ISSUE THREAD

**Issue by ggggamer** [ggggamer/AssetPreview#27]
- [ ] Add emitter and bullet script handle.

- [ ] Use user selected node for bullet view.

- [ ] Show emitter group and emitter's pos.

- [ ] Manage bullets, emitters, and emiter groups's reference count.
