### ISSUE TITLE
TODO: Cocos Studio schema

### ISSUE THREAD

**Issue by ggggamer** [ggggamer/AssetPreview#8]
- [ ] ParticleObjectData

- [ ] TextObjectData

- [ ] TextAtlasObjectData

- [ ] CheckBoxObjectData

- [ ] ScrollViewObjectData

**Comment by ggggamer** [comment]
- [ ] CheckBoxObjectData

**Comment by ggggamer** [comment]
- [ ] Custom Button Widget: File, op, normal, selectOp, select, ed.

- [ ] Custom ImageNumber Widget: set label interval.

- [ ] Custom Scale9Sprite: center area is repeat by UV.

- [ ] ProgressTimer diff with editor when select "Right to Left".

- [ ] Didn't handle PList Texture.
